name: "_Build Mayhem"

on:
  workflow_call:
    inputs:
      mcode-branch:
        type: string
        required: true
        description: "mcode branch"
      mcode-commit-sha:
        type: string
        description: "mcode commit SHA (optional)"

    outputs:
      component-affected-analyze:
        value: "${{ jobs.component-affected.outputs.analyze }}"
        description: "'analyze' component or its dependencies have been affected by changes on this branch."
      component-affected-api:
        value: "${{ jobs.component-affected.outputs.api }}"
        description: "'api' component or its dependencies have been affected by changes on this branch."
jobs:
  component-affected:
    runs-on: ubuntu-22.04
    env:
      ON_MAIN_OR_RELEASE_BRANCH: ${{ inputs.mcode-branch == 'main' || startsWith(inputs.mcode-branch, 'release-') }}
    outputs:
      analyze : ${{ env.ON_MAIN_OR_RELEASE_BRANCH   == 'true'
                    || !github.event.before
                    || steps.filter.outputs.analyze == 'true' }}

      api     : ${{ env.ON_MAIN_OR_RELEASE_BRANCH   == 'true'
                    || !github.event.before
                    || steps.filter.outputs.api     == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "${{ inputs.mcode-commit-sha || inputs.mcode-branch }}"

      - run: echo "github.event.before=${{ github.event.before }}"
      - run: echo "env.ON_MAIN_OR_RELEASE_BRANCH=${{ env.ON_MAIN_OR_RELEASE_BRANCH == 'true' }}"

      - name: Resolve affected components
        if: ${{ github.event.before || env.ON_MAIN_OR_RELEASE_BRANCH == 'true' }}
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2
        id: filter
        with:
          filters: |
            analyze:
              - 'analyze/**'
            api:
              - 'api/**'
