name: Build

on:
  push: {}

jobs:
  job-0:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi

  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            await octokit.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              "validate.yaml",
              "${{ github.ref_name }}"
            });
