name: Build

on:
  push: {}

jobs:
  component-affected:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi

  job-1:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "validate.yaml",
              ref: "${{ github.ref_name }}",
              inputs: {
                test_analyze: needs.component-affected.outputs.analyze,
                test_api: needs.component-affected.outputs.api,
                test_mchart: needs.component-affected.outputs.api,
              }
            });
