on:
  push:
    branches: ['main', 'feature']

concurrency:
  # this will enable all builds on `main` run concurrently and not be cancelled
  # while on any other branch builds will be serialized and ones in progress may
  # be cancelled if there are newer commits
  group: ${{ format('{0}-{1}', github.workflow, github.ref_name == 'main' && github.run_id || github.head_ref || github.ref_name) }}
  cancel-in-progress: true

jobs:
  job-0:
    runs-on: ubuntu-22.04
    steps:
      - run: echo begin, group=${{ format('{0}-{1}', github.workflow, github.ref_name == 'main' && github.run_id || github.head_ref || github.ref_name) }}

  job-1:
    needs: job-0
    runs-on: ubuntu-22.04
    steps:
      - run: sleep 60

  job-2:
    needs: job-1
    runs-on: ubuntu-22.04
    steps:
      - run: echo endh
