on:
  push:
    branches: ['main', 'feature']

# we want to cancel builds for old commits on feature branches
# to avoid overloading build servers, but NOT do that for "main" & "release-*" ones
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}
# cancel-in-progress: ${{ github.ref_name != 'main' && !startsWith(github.ref_name, 'release-') }}

jobs:
  job-0:
    runs-on: ubuntu-22.04
    steps:
      - run: echo step-0
      - run: sleep 300 # 5 minutes
      - run: echo step-1
