name: "Continuous deployment"
run-name: "Continuous deployment from ${{ github.event.workflow_run.head_branch }}"

on:
  workflow_dispatch:

  workflow_run:
    workflows: [Build]
    types: [completed]
    branches:
      - yet-another-branch
      - and-yet-another-branch

jobs:
  deploy:
    if: ${{ !github.event.workflow_run
            || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Run C/D on yet-another-branch
        uses: actions/github-script@v3.1.0
        if: ${{ github.event.workflow_run.head_branch == 'yet-another-branch' }}
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "deploy.yaml",
              ref: "yet-another-branch"
            });
