name: "Continuous deployment from ${{ github.event.workflow_run.head_branch }}"

on:
  workflow_dispatch:

  workflow_run:
    workflows: [Build]
    types: [completed]
    branches:
      - yet-another-branch
      - and-yet-another-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: gh workflow run deploy.yaml --ref yet-another-branch
        if: ${{ github.event.workflow_run.head_branch == 'yet-another-branch' }}
