name: "Deploy / staging.forallsecure.com"

on:
  workflow_dispatch:

  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

jobs:
  deploy-staging-forallsecure-com-on-success:
    runs-on: ubuntu-22.04
    steps:
      - run: echo success
      - run: echo head-sha ${{ github.event.workflow_run.head_sha || 'main' }}
