name: "Deploy"
run-name: "Deploy (${{ github.ref_name }})"

on:
  workflow_dispatch:

  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [yet-another-branch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: gh workflow run deploy.yaml --ref yet-another-branch
