name: "Deploy"
run-name: "Deploy (${{ github.ref_name }})"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: echo deploying
