name: Extra

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

jobs:
  job-0:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello from workflow_run ${{ github.event.workflow_run.head_sha }}
