name: "Scheduling"
run-name: "Scheduling (${{ github.ref_name }})"

on:
  #schedule:
  #  cron: xxxx

  workflow_run:
    workflows: [Workload]
    types: [completed]
#    branches:
#      - yet-another-branch
#      - and-yet-another-branch

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  scheduler:
#    if: ${{ !github.event.workflow_run
#            || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Run C/D on yet-another-branch
        uses: actions/github-script@v6
        #if: ${{ github.event.workflow_run.head_branch == 'yet-another-branch' }}
        with:
          debug: true
          script: |
            const branchesToService = ["main", "release"];

            const workloadWorkflow = "workload.yaml";

            const inProgressWorkflowRunListResponse = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workloadWorkflow,
              per_page: 0,
              exclude_pull_requests: true,
              status: "in_progress"
            });

            const queuedWorkflowRunListResponse = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workloadWorkflow,
              per_page: 0,
              exclude_pull_requests: true,
              status: "queued"
            });

            const activeWorkflowRunCount =
              inProgressWorkflowRunListResponse.data.total_count
              + queuedWorkflowRunListResponse.data.total_count;

            console.log("activeWorkflowRunCount=", activeWorkflowRunCount);

            if (activeWorkflowRunCount) {
              console.log(`terminating: ${activeWorkflowRunCount} ${workloadWorkflow} workflow runs still active (in_progress+queued)`);
              return 0;
            }

            console.log("branchesToService" + JSON.stringify(branchesToService));

            const completedWorkflowRunListResponse =
              await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workloadWorkflow,
                per_page: branchesToService.length,
                exclude_pull_requests: true,
                status: "completed"
              });

            const lastServicedBranches =
              completedWorkflowRunListResponse.data.workflow_runs.map(
                wr => wr.head_branch);

            console.log("lastServicedBranches=" + JSON.stringify(lastServicedBranches));

            let nextBranchToService = null;
            for (const b of branchesToService) {
              if (lastServicedBranches.indexOf(b) < 0) {
                nextBranchToService = b;
                break;
              }
            }

            console.log(nextBranchToService);

            if (nextBranchToService) {
              console.log("scheduling a run to service next branch: " + nextBranchToService);

              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workloadWorkflow,
                ref: nextBranchToService
              });
            }
