name: Set Build Status

on:
  workflow_dispatch:
    inputs:
      sha:
        type: string

  workflow_run:
    workflows: [Test]
    types: [completed]
    branches:
      - main

jobs:
  set-build-status:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'workflow_run' }}
        run: |
          echo via workflow run
          echo github.event.workflow_run.name=${{ github.event.workflow_run.name }}
          echo github.event.workflow_run.artifacts_url=${{ github.event.workflow_run.artifacts_url }}
          echo github.event.workflow_run.head_branch=${{ github.event.workflow_run.head_branch }}
          echo github.event.workflow_run.head_sha=${{ github.event.workflow_run.head_sha }}
          echo 'github.event.workflow_run=${{ toJSON(github.event.workflow_run) }}'
          echo 'github.event.workflow=${{ toJSON(github.event.workflow) }}'

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo via workflow dispatch
