name: Test

on:
  push: {}

jobs:
  job-0:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          GH_ACTIONS_CHECK_SUITE_ID=$(gh api \
            "/repos/razzmatazz/gh-actions-playground/commits/${{ github.sha }}/check-suites?app_id=15368" \
            --jq '.check_suites[].id')

          echo GH_ACTIONS_CHECK_SUITE_ID=$GH_ACTIONS_CHECK_SUITE_ID >> $GITHUB_ENV

      - run: echo $GH_ACTIONS_CHECK_SUITE_ID

      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            "/repos/razzmatazz/gh-actions-playground/commits/${{ github.sha }}/check-runs" \
            -f name="mighty_readme" \
            -f head_sha=${{ github.sha }} \
            -f status=in_progress \
            -f external_id=my-check \
            -f output.title="Mighty Readme report" \
            -f output.summary="" \
            -f output.text=""
