name: Test

on:
  push: {}

  workflow_dispatch: {}

jobs:
  job-0:
    uses: ./.github/workflows/_build-mayhem.yaml
    secrets: inherit
    with:
      mcode-branch: "${{ github.head_ref || github.ref_name }}"
      mcode-commit-sha: "${{ github.event.workflow_run.head_sha }}"

  job-1:
    needs: job-0
    runs-on: ubuntu-22.04
    steps:
      - run: echo test
