name: Test

on: push

jobs:
  job-0:
    uses: ./.github/workflows/_build-mayhem.yaml
    secrets: inherit
    with:
      mcode-branch: "${{ github.head_ref || github.ref_name }}"
      mcode-commit-sha: "${{ github.event.workflow_run.head_sha }}"
