name: Test

on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          pip3 install coverage

      - run: |
          python3 -m coverage run -m unittest
          python3 -m coverage xml -o cobertura.xml

      - uses: 5monkeys/cobertura-action@master
        with:
          path: cobertura.xml
          minimum_coverage: 75
