name: Test
run-name: "Test (${{ github.ref_name }})"

on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      check_run_id: ${{ steps.create_check_run.outputs.result }}
    steps:
    - id: create_check_run
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const sleep = ms => new Promise(r => setTimeout(r, ms));

          const checkRunSha = "${{ github.sha }}";

          await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            status: "completed",
            conclusion: "failure",
            name: "build-checks:test:main",
            head_sha: checkRunSha
          });

          await sleep(2000);

          await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            status: "completed",
            conclusion: "success",
            name: "build-checks:test:main",
            head_sha: checkRunSha
          });

          const checkRunListResponse = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: checkRunSha,
            check_name: "build-checks:test:main"
          });

          console.log("keys(data)=" + JSON.stringify(Object.keys(checkRunListResponse.data)));
