on:
  push:
    branches: ['main']

jobs:
  job-0:
    runs-on: ubuntu-22.04
    steps:
      - run: echo job-0

  job-1:
    runs-on: ubuntu-22.04
    steps:
      - run: echo job-1

      # simulate job failure
      - run: exit 1

  aggregate-job:
    needs: [job-0, job-1]
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - run: echo aggregate-job

      - name: Check for dependent test failure(s)
      - run: exit 1
        if: |
          needs.job-0.result == 'failure' ||
          needs.job-1.result == 'failure'
