name: Test
run-name: "Test (${{ github.ref_name }})"

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - run: echo "force=${{ inputs.force && 'yes' || 'no' }}"
