on:
  push:
    branches:
      - 'main'

jobs:
  job-0:
    runs-on: ubuntu-22.04
    container:
      image: "debian"
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: apt-get update && apt-get install -y curl jq

      - run: mkdir -p ./workdir/sca && cp attack_surface.txt ./workdir/sca/attack_surface.txt

      - name: Produce env.ATTACK_SURFACE_QUOTED
        run: |
          set -eux
          printf 'ATTACK_SURFACE_QUOTED="%s"' "$(cat ./workdir/sca/attack_surface.txt | jq -Rs '.')" >> $GITHUB_ENV

      - name: "Post to #engineering-feed"
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ENGINEERING_FEED }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "CVE Report, ${{ github.ref_name }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ env.ATTACK_SURFACE_QUOTED }}
                  }
                }
              ]
            }
