name: Test
run-name: "Test (${{ github.ref_name }})"

on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      check_run_id: ${{ steps.create_check_run.outputs.result }}
    steps:
    - id: create_check_run
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const checkRunSha = "${{ github.sha }}";


          const conclusion = (Math.random() > 0.5) ? "success" : "failure";

          const createCheckRunResponse =
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: "completed",
              conclusion: conclusion,
              name: "build-checks:test:main",
              head_sha: checkRunSha
            });

          const checkRun = createCheckRunResponse.data;

          console.log(
            `an new checkrun #${checkRun.id} was inserted w/conclusion=${conclusion}: `
            + `https://github.com/razzmatazz/gh-actions-playground/runs/${checkRun.id}`);

          return checkRun.id
