name: Test

on:
  push: {}

jobs:
  job-0:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          GH_ACTIONS_CHECK_SUITE_ID=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/razzmatazz/gh-actions-playground/commits/${{ github.sha }}/check-suites?app_id=15368" \
            --jq '.check_suites[].id')

          echo GH_ACTIONS_CHECK_SUITE_ID=$GH_ACTIONS_CHECK_SUITE_ID >> $GITHUB_ENV

      - run: echo $GH_ACTIONS_CHECK_SUITE_ID

      - run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/razzmatazz/gh-actions-playground/commits/${{ github.sha }}/check-runs" \
            -d '{"name":"mighty_readme","head_sha":"${{ github.sha }}","status":"in_progress","external_id":"my-check","output":{"title":"Mighty Readme report","summary":"","text":""}}'
