on:
  push:
    branches:
      - 'main'

jobs:
  job-0:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: |
          set -eux
          echo ATTACK_SURFACE="$(cat attack_surface.txt)" >> $GITHUB_ENV

      - run: |
          set -eux
          echo |
            {"item": { "${{ env.ATTACK_SURFACE }}" } }""
