on:
  push:
    branches:
      - 'main'

jobs:
  job-0:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: |
          curl -Lqs https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 --output jq-linux64

      - run: |
          set -eux
          echo ATTACK_SURFACE="$(cat x | ./jq-linux64 -Rs '.')" >> $GITHUB_ENV

      - run:
          echo ${{ env.ATTACK_SURFACE }}

      - run:
          echo ${{ toJSON(env.ATTACK_SURFACE) }}

      - run: |
          set -eux
          echo ${{ env.ATTACK_SURFACE }}
