name: Test

on:
  push: {}

jobs:
  job-0:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          GH_ACTIONS_CHECK_SUITE_ID=$(gh api \
            "/repos/razzmatazz/gh-actions-playground/commits/${{ github.sha }}/check-suites?app_id=15368" \
            --jq '.check_suites[].id')

          echo GH_ACTIONS_CHECK_SUITE_ID=$GH_ACTIONS_CHECK_SUITE_ID >> $GITHUB_ENV

      - run: echo $GH_ACTIONS_CHECK_SUITE_ID

      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -X POST \
            "/repos/razzmatazz/gh-actions-playground/check-runs" \
            -f name="artifacts:base-images" \
            -f head_sha=${{ github.sha }} \
            -f status=completed \
            -f conclusion=success \
            -f external_id=my-check \
            -f output[title]="Mighty Readme report" \
            -f output[summary]="fheiojfeoiwfew==hi==\\nfjeiofew" \
            -f output[text]="jfeiojfiowe fjiowjf eow text txt\n==fewfewfew==\nfewijifoew"

      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --paginate \
            "/repos/razzmatazz/gh-actions-playground/check-suites/$GH_ACTIONS_CHECK_SUITE_ID/check-runs"
