name: Test

on:
  push: {}

jobs:
  job-0:
    runs-on: ubuntu-latest
    steps:
      - id: list-check-suites
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --paginate \
            /repos/razzmatazz/gh-actions-playground/commits/0c4a1c281e26db46301a3c0650b84ecd0fd69eaa/check-suites \
          | jq '.'

      - run: ${{ steps.list-check-suites.outputs.stdout }}
