name: Test

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - run: id
    - run: sudo apt-get update

    - run: find /home/runner

    - run: ls -lh /home/runner

    - run: ps ax
