on:
  push:
    branches:
      - 'main'

jobs:
  job-0:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: |
          curl -Lqs https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 --output jq-linux64 \
            && (echo "af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44 jq-linux64" | sha256sum -c)
            && chmod +x jq-linux64 \
            && ./jq-linux64 --version

      - run: echo -en "fje\nfewjiofew\n\nfejiofwe" > x

      - run: |
          set -eux
          echo ATTACK_SURFACE="$(cat x | ./jq-linux64 -Rs '.')" >> $GITHUB_ENV

      - run:
          echo ${{ env.ATTACK_SURFACE }}

      - run:
          echo ${{ toJSON(env.ATTACK_SURFACE) }}

      - run: |
          set -eux
          echo ${{ env.ATTACK_SURFACE }}
