name: Test

on:
  push: {}

  workflow_dispatch: {}

jobs:
  job-0:
    if: true
    runs-on: ubuntu-22.04
    steps:
      - run: echo job-0

  job-1:
    needs: job-0
    runs-on: ubuntu-22.04
    steps:
      - run: echo job-1
