on:
  push:
    branches: ['main']

jobs:
  job-0:
    runs-on: ubuntu-22.04
    steps:
      - run: echo job-0

  job-1:
    runs-on: ubuntu-22.04
    steps:
      - run: echo job-1

      # simulate job failure
      - run: exit 1

  aggregate-job:
    needs: [job-0, job-1]
    runs-on: ubuntu-22.04
    if: always()
    strategy:
      matrix:
        job: ${{ needs }}
    steps:
      - name: Check for dependent job failure(s)
        run: exit 1
        if: ${{ matrix.job.result == 'failure' || matrix.job.result == 'cancelled' }}
