name: Test

on:
  push: {}

jobs:
  job-0:
    runs-on: ubuntu-latest
    steps:
      - id: list-check-suites
        outputs:
          gh_actions_check_suite_id: ${{ env.GH_ACTIONS_CHECK_SUITE_ID }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --paginate \
            "/repos/razzmatazz/gh-actions-playground/commits/${{ github.sha }}/check-suites?app_id=15368" \
          | jq '.check_suites[].id'
