on:
  push:
    branches:
      - 'main'

jobs:
  job-0:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: mkdir -p ./workdir/sca && cp attack_surface.txt ./workdir/sca/attack_surface.txt

      - name: Download jq
        run: |
          set -eux
          curl -Lqs https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 --output jq-linux64 \
            && (echo "af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44 jq-linux64" | sha256sum -c) \
            && chmod +x jq-linux64 \
            && ./jq-linux64 --version

      - name: Produce env.ATTACK_SURFACE_QUOTED
        run: |
          set -eux
          echo ATTACK_SURFACE_QUOTED="$(cat ./workdir/sca/attack_surface.txt | ./jq-linux64 -Rs '.')" >> $GITHUB_ENV

      - name: "Post to #engineering-feed"
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ENGINEERING_FEED }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "CVE Report, ${{ github.ref_name }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ env.ATTACK_SURFACE_QUOTED }}
                  }
                }
              ]
            }
