name: Test

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - run: id
    - run: sudo apt-get update

    - run: find /opt/runner

    - run: ls -lh /opt/runner
    - run: ls -lh /opt/runner/provisioner

    - run: ps ax
