name: Validate

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  job-0:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello from workflow_run ${{ github.event.workflow_run.head_sha }}

  mark-check-in-progress:
    needs: job-0
    name: Mark check in-progress
    runs-on: ubuntu-latest
    permissions:
      checks: write
    outputs:
      check_run_id: ${{ steps.create-check.outputs.result }}
    steps:
      - name: 'Set check status in-progress'
        uses: actions/github-script@v3.1.0
        id: create-check
        with:
          script: |
            const check = await github.checks.create({
               owner: context.repo.owner,
               repo: context.repo.repo,
               name: "Validate",
               head_sha: "${{ github.event.workflow_run.head_sha }}",
               details_url: "http://github.com/",
               status: "in_progress",
               output: {
                  title: "Validate",
                  summary: "Validation summary.",
                  text: '',
               },
            });

            console.log("check.data=", JSON.stringify(check.data));

            return check.data.id

  sleep:
    needs: mark-check-in-progress
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10

  mark-check-as-completed:
    needs:
      - mark-check-in-progress
      - sleep
    name: Mark check as completed
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - run: echo "check-id = ${{ needs.mark-check-in-progress.outputs.check_run_id }}"

      - name: 'Update check status in-progress'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            await github.checks.update({
               owner: context.repo.owner,
               repo: context.repo.repo,
               check_run_id: ${{ needs.mark-check-in-progress.outputs.check_run_id }},
               status: "completed",
               conclusion: failure"
            });
